import React from 'react';
import '../styles/Footer.css';

/**
 * Footer Component
 * Renders copyright info and simple system metadata.
 */
export default function Footer() {
  return (
    <footer className="app-footer">
      <div className="footer-content">
        <p className="footer-text">
          &copy; {new Date().getFullYear()} Snakify. Powered by TensorFlow, MobileNetV2, and FastAPI.
        </p>
        <div className="footer-links">
          <a 
            href="#privacy" 
            onClick={(e) => {
              e.preventDefault();
              alert("This local web application processes all uploaded images on your local machine and backend server. No personal data is stored or transmitted to external third-party hosts.");
            }}
          >
            Privacy Policy
          </a>
          <a 
            href="#disclaimer" 
            onClick={(e) => {
              e.preventDefault();
              alert("All classifications are predictions generated by a machine learning model. If a bite occurs, call emergency services immediately.");
            }}
          >
            Liability Disclaimer
          </a>
        </div>
      </div>
    </footer>
  );
}
